[package]
authors = ["cyqsimon <28627918+cyqsimon@users.noreply.github.com>"]
categories = ["command-line-utilities", "filesystem"]
description = "Rename files to randomly generated strings."
edition = "2021"
keywords = ["random", "rename", "filetool"]
license = "AGPL-3.0-only"
name = "rng-rename"
repository = "https://github.com/cyqsimon/rng-rename"
version = "0.2.0"

[dependencies]
ansi_term = "0.12.1"
clap = {version = "3.0.13", features = ["derive", "unicode"]}
derivative = "2.2.0"
dialoguer = "0.9.0"
itertools = "0.10.3"
log = "0.4.14"
rand = "0.8.4"
sanitize-filename = "0.3.0"
simple_logger = "2.1.0"
# strum = {version = "0.23.0", features = ["derive"]}
