[package]
authors = ["cyqsimon <28627918+cyqsimon@users.noreply.github.com>"]
description = "Rename files to randomly generated strings."
edition = "2021"
keywords = ["random", "rename", "filetool"]
name = "random-rename"
version = "0.1.0"

[dependencies]
ansi_term = "0.12.1"
clap = {version = "3.0.13", features = ["derive", "unicode"]}
dialoguer = "0.9.0"
itertools = "0.10.3"
log = "0.4.14"
rand = "0.8.4"
simple_logger = "2.1.0"
strum = {version = "0.23.0", features = ["derive"]}
