[package]
authors = ["cyqsimon <28627918+cyqsimon@users.noreply.github.com>"]
categories = ["command-line-utilities", "filesystem"]
description = "Rename files to randomly generated strings."
edition = "2021"
exclude = ["/res"]
keywords = ["random", "rename", "filetool"]
license = "AGPL-3.0-only"
name = "rng-rename"
repository = "https://github.com/cyqsimon/rng-rename"
version = "0.5.2"

[dependencies]
ansi_term = "0.12.1"
clap = {version = "4.1.7", features = ["cargo", "derive", "unicode"]}
clap-verbosity-flag = "2.0.0"
clap_complete = "4.1.4"
derivative = "2.2.0"
dialoguer = "0.10.3"
itertools = "0.10.5"
log = "0.4.17"
rand = "0.8.5"
sanitize-filename = "0.4.0"
simple_logger = "4.0.0"
# strum = {version = "0.23.0", features = ["derive"]}
